### ISSUE TITLE
Update to Velocity 3.0.0

### ISSUE THREAD

**Issue by Glucy-2** [xElementzx/VelocityUuidGetter#2]
````py
[19:40:56 INFO] [velocityuuidgetter]: VelocityUuidGetter Loaded!
[19:40:56 ERROR]: Couldn't pass ProxyInitializeEvent to velocityuuidgetter
>java.lang.NoSuchMethodError: 'void com.velocitypowered.api.command.CommandManager.register(com.velocitypowered.api.command.Command, java.lang.String[])'
at me.xelementzx.velocityuuidgetter.VelocityUuidGetter.onProxyInitialize(VelocityUuidGetter.java:28) ~[?:?]
at me.xelementzx.velocityuuidgetter.Lmbda$18.execute(Unknown Source) ~[?:?]
at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity-3.0.0.jar:3.0.0]
at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:587) ~[velocity-3.0.0.jar:3.0.0]
at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$6(VelocityEventManager.java:468) ~[velocity-3.0.0.jar:3.0.0]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
at java.lang.Thread.run(Unknown Source) [?:?]
````

**Comment by xElementzx** [comment]
Bumped to Version 1.1.0 which has 3.0.0 Support.
